version: '3'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: escolha_uma_senha
    web:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - .:/minha-aplicacao
        ports:
            - '3000:3000'
        depends_on: 
            - db